<?php
	$BankList = array();
	$BankList["BOC"]="中国银行";
	$BankList["ABC"]="农业银行";
	$BankList["CCB"]="建设银行";
	$BankList["ICBC"]="工商银行";	
	$BankList["CMB"]="招商银行";
	$BankList["CITIC"]="中信银行";
	$BankList["CMBC"]="民生银行";
	$BankList["CIB"]="兴业银行";
	$BankList["CEB"]="光大银行";
	$BankList["BOS"]="上海银行";
	$BankList["PSBC"]="中国邮储银行";
	$BankList["SZPAB"]="平安银行";
	$BankList["SPDB"]="浦东发展银行";
	$BankList["COMM"]="交通银行";
	$BankList["GDB"]="广东发展银行";
	$BankList["HXB"]="华夏银行";	
?>